config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :carts
  # root "products#index"
  root 'store#index', as: 'store_index'
  get 'store/index'
  resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  
  validates :title, presence: true, uniqueness: true
  validates :price, presence: true 
  validates :description, presence: true 

  mount_uploader :image_url_1, ProductImageUploader
  mount_uploader :image_url_2, ProductImageUploader
  mount_uploader :image_url_3, ProductImageUploader
  mount_uploader :image_url_4, ProductImageUploader
  mount_uploader :image_url_5, ProductImageUploader

  has_many :order_items
  before_destroy :ensure_not_referenced_by_any_line_item
#...
  private
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless order_items.empty?
      errors.add(:base, 'Order Items present')
      throw :abort
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base

  private

    def cart_params
      params.require(:cart).permit()
    end

end

app/controllers/concerns/current_cart.rb
module CurrentCart
  
  private
  
  def set_cart
    @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound

    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < InheritedResources::Base

  private

    def order_item_params
      params.require(:order_item).permit(:product_id, :cart_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  private

    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url_1, :image_url_2, :image_url_3, :image_url_4, :image_url_5, :is_featured, :is_sold_out, :collection_date)
    end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>

<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>

  <%= button_to "Destroy this cart", @cart, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Votre Magasin de Pagnes Africains</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application',        'data-turbolinks-track': 'reload' %> 
  </head>

<body>
 <header class="main">
    <%# <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %> 
    <h1><%= @page_title %></h1>
  </header>
  <section class="content">
    <nav class="side_nav">
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/questions">Questions</a></li>
        <li><a href="/news">News</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>
    </nav>
    <main class='<%= controller.controller_name %>'>
      <%= yield %>
    </main>
  </section>
</body>
</html>

app/views/order_items/_form.html.erb
<%= simple_form_for(@order_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :product %>
    <%= f.association :cart %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/order_items/_order_item.html.erb
<div id="<%= dom_id order_item %>">
  <p>
    <strong>Product:</strong>
    <%= order_item.product_id %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= order_item.cart_id %>
  </p>

</div>

app/views/order_items/edit.html.erb
<h1>Editing order item</h1>

<%= render "form", order_item: @order_item %>

<br>

<div>
  <%= link_to "Show this order item", @order_item %> |
  <%= link_to "Back to order items", order_items_path %>
</div>

app/views/order_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Order items</h1>

<div id="order_items">
  <% @order_items.each do |order_item| %>
    <%= render order_item %>
    <p>
      <%= link_to "Show this order item", order_item %>
    </p>
  <% end %>
</div>

<%= link_to "New order item", new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New order item</h1>

<%= render "form", order_item: @order_item %>

<br>

<div>
  <%= link_to "Back to order items", order_items_path %>
</div>

app/views/order_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_item %>

<div>
  <%= link_to "Edit this order item", edit_order_item_path(@order_item) %> |
  <%= link_to "Back to order items", order_items_path %>

  <%= button_to "Destroy this order item", @order_item, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :image_url_1 %>
    <%= f.input :image_url_2 %>
    <%= f.input :image_url_3 %>
    <%= f.input :image_url_4 %>
    <%= f.input :image_url_5 %>
    <%= f.input :is_featured %>
    <%= f.input :is_sold_out %>
    <%= f.input :collection_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Image url 1:</strong>
    <%= product.image_url_1 %>
  </p>

  <p>
    <strong>Image url 2:</strong>
    <%= product.image_url_2 %>
  </p>

  <p>
    <strong>Image url 3:</strong>
    <%= product.image_url_3 %>
  </p>

  <p>
    <strong>Image url 4:</strong>
    <%= product.image_url_4 %>
  </p>

  <p>
    <strong>Image url 5:</strong>
    <%= product.image_url_5 %>
  </p>

  <p>
    <strong>Is featured:</strong>
    <%= product.is_featured %>
  </p>

  <p>
    <strong>Is sold out:</strong>
    <%= product.is_sold_out %>
  </p>

  <p>
    <strong>Collection date:</strong>
    <%= product.collection_date %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Liste des Pagnes</h1>

<table>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to 'New Product', new_product_path %>
      </td>
    </tr>
  </tfoot>
<tbody>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td class="image">
        <%= image_tag(product.image_url_1.url, class: 'list_image', width:  "50%") %>
      </td>

      <td class="description">
        <h1><%= product.title %></h1>
        <p>
          <%= truncate(strip_tags(product.description),
          length: 80) %>
        </p>
      </td>

      <td class="actions">
        <ul>
          <li><%= link_to 'Show', product %></li>
          <li><%= link_to 'Edit', edit_product_path(product) %></li>
          <li>
            <%= link_to 'Destroy',
            product,
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
          </li> 
        </ul>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/store/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Votre Catalogue de Pagnes</h1>

<ul class="catalog">
  <% cache @products do %>
    <% @products.each do |product| %>
      <% cache product do %>
        <li>
          <%= image_tag(product.image_url_1.url) %>
          <h2><%= product.title %></h2>
          <p>
            <%= sanitize(product.description) %>
          </p>
          <div class="price">
            <%= number_to_currency(product.price) %>
            <%= button_to 'Add to Cart', order_items_path(product_id: product) %>

            <%# <%= product.price %>
          </div>
        </li>      
      <% end %>
    <% end %>
  <% end %>
</ul>